let distinctCountries = [
  'Norge',
  'Danmark',
  'Tyskland',
  'Portugal',
  'Finland',
  'Sverige',
  'Frankrike',
  'Hellas',
  'Skottland',
  'Italia',
  'USA',
  'Irland',
  'Canada',
  'Nederland',
  'England',
  'Mexico',
  'Spania',
  'Chile',
  'Australia',
  'Sør-Afrika',
  'New Zealand',
  'Østerrike',
  'Ungarn',
  'Cuba',
  'Argentina',
  'Island',
  'Belgia',
  'Guatemala',
  'Jamaica',
  'Bermuda',
  'Polen',
  'Antillene',
  'Moldova',
  'Storbritannia',
  'Japan',
  'India',
  'Dominik. rep.',
  'Peru',
  'Taiwan',
  'Barbados',
  'Latvia',
  'Sveits',
  'Georgia',
  'EU',
  'Libanon',
  'Brasil',
  'Estland',
  'Colombia',
  'Nicaragua',
  'Guyana',
  'Haiti',
  'Venezuela',
  'Tsjekkia',
  'Makedonia',
  'Slovenia',
  'Marokko',
  'Øvrige',
  'Thailand',
  'Martinique',
  'Luxemburg',
  'Bosnia-Herceg.',
  'Tyrkia',
  'Russland',
  'Ukraina',
  'Bulgaria',
  'Romania',
  'St. Chr.& Nevis',
  'Uruguay',
  'Litauen',
  'Puerto Rico',
  'Panama',
  'Slovakia',
  'Israel',
  'Montenegro',
  'Kroatia',
  'Sør-Korea',
  'Kina',
  'Paraguay',
  'Nord Irland'
];

let distinctPackaging = [
  'Glass',
  'Plast',
  'Bag-in-box',
  'Pouch',
  'Emballasje med pant',
  'Metall',
  'Øvrig',
];

let distinctProductSelection = [
  'Basisutvalget',
  'Bestillingsutvalget',
  'Testutvalget',
  'Partiutvalget'
];

module.exports = { distinctCountries: distinctCountries, distinctPackaging: distinctPackaging, distinctProductSelection: distinctProductSelection };